### ISSUE TITLE
[Request] UI Suggestions - A few minor things

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#210]
I have just a few suggestions for the UI to make them more in-line with what people are used to.  When the submission info window pulls up after a disc is dumped:

* For the drop-down selections, such as 'Category' and 'Region', if you could type the first letter (say J for Japan) and it would automatically move toward that selection (and then if you press J again it goes to the next item), that would be a bit quicker and easier, and more in-line with other UI for drop-downs, similar to when submitting a disc on the forum.  

* Similar to above, if you could do this for languages, and then use spacebar to select that item, that would be cool.  

Essentially, both of the above would enable you to go through most of the items without having to revert to the mouse, then back to keyboard.  Just small QOL improvements to make it a bit quicker / easier.

**Comment by InternalLoss** [comment]
As there's already a UI suggestion issue open, I'd also like to add - for Dual-layer DVDs (my example is the Xbox 360 DVDs), the ring codes mention "L0" and "L1". Obviously, those who dump *a lot* will probably be able to infer which way around, but I find myself having to exit and then edit the text file since it says Inner/Outer. Maybe L0 and L1 should be swapped out for Inner/Outer? it'd make more sense to those who are beginners.

**Comment by mnadareski** [comment]
I mentioned these in Discord but I'll echo it here for clarity:
- For the dropdowns not doing the "first letter" search, I literally have no idea how to do this. I'm going to add the "Help Wanted" tag to this in case anyone who's better with UI design to help me there
- For the L0 and L1, those are *technically* the correct names for those, but I can see how it would be difficult to track for newbies. I'll have to figure out the best way to approach this since creating a fully adaptive UI for each disc type (which has been asked for in the past) is beyond my ability.

**Comment by mnadareski** [comment]
Follow-up to this finally:
- Still no luck on the dropdowns. I did find some things that could work, but none of them ended up functioning the way I'd expect
- For the L0 and L1 naming, the combination of https://github.com/SabreTools/MPF/commit/24ce4bcc5187bd7ed29591a181c464ffe70fbfe7 and https://github.com/SabreTools/MPF/commit/ecb0234258908abab4d09149b24ebaf44df05586 should take care of that

**Comment by mnadareski** [comment]
The type to seek part should be taken care of by https://github.com/SabreTools/MPF/commit/c8cfe76aa33215f81a81f9de636dbeaa675dc3b5

That should just leave the select by space bar, which I have not tried.

**Comment by mnadareski** [comment]
I think all of this has been taken care of. Further things can come up in a new issue.
