### ISSUE TITLE
[Request] dumping a disc more than one time

### ISSUE THREAD

**Issue by Madroms** [SabreTools/MPF#240]
It is possible to add an option that let you choose how many dump you want to make ?
I always dump discs 1 time for a verification, but 2 times for a new entry on redump.

If adding this option (by default = 1), you will need to update automatically the output filename each time (but not necessarily the output directory).

Example:
If 1 dump to make:
output filename: mydump.bin
output directory: ISO\mydump

If 2 dumps to make:
output filename of the 1st dump: mydump (1).bin
output filename of the 2nd dump: mydump (2).bin
output directory: ISO\mydump

**Comment by mnadareski** [comment]
Related to https://github.com/SabreTools/DICUI/issues/183

**Comment by mnadareski** [comment]
This is another I'm going to leave open into oblivion because this would require way WAY more effort than I'm willing to put in to ensure that the UI is entirely out of the loop once the dump starts. My concerns would be around cancelling existing dumping.

Aaru and DIC may also cause issues if you're dumping to the same spot at the same time, and I really don't want to deal with DIC's oddities any more than I have to. Again, if someone else wants to find a reasonable way of implementing this, feel free to open a PR.

**Comment by mnadareski** [comment]
Conversation on discord showed that I apparently can't read. This was a request to dump the same disc multiple times in a row. That being said, I'm still leaving this open for extra assistance, since that's not something I'm inherently comfortable adding.

**Comment by mnadareski** [comment]
Both this and the related item are not up for debate anymore. MPF will neither stop you from creating multiple instances nor recommend that you do. Users who choose to do one or the other will have to deal with how their computer handles that situation.
