### ISSUE TITLE
[Request] pre / post batch files

### ISSUE THREAD

**Issue by Madroms** [SabreTools/MPF#242]
Is it possible to add an option that let you launch/call an external file after (and maybe before) the "start dumping" process ?

Example:
It could be useful to call a batch file that could be launched after the dump process, to make some tasks like making some compressed files (one for logs only, one with all the files, one with only .img, only .scm, etc.), deleting files after compression, moving them, etc.

You could also add this on DICUI but probably too many cases (zip, 7z, rar, etc. On windows, other Oses, etc.).

**Comment by mnadareski** [comment]
I'm going to leave this open, but I'm not going to implement this for the following reasons:
- It's already bad enough that I have to wrap DIC and Aaru the way that I do. A more coupled approach is what I'd want instead, but I have to do it this way for now.
- This same functionality can be achieved by using Check, since in one of the more recent releases, check gained the ability to specify a drive path for doing things like copy protect scan and additional information extraction. Having that sort of batch will give you way more flexibility than the UI.
- The UI is supposed to be meant for "the most common case" scenarios. Specialty things like that should be handled elsewhere.

I am leaving this open if someone else is willing to put the time into making this feasible.

**Comment by mnadareski** [comment]
I'm officially closing this. This didn't fit into the idea of DICUI when it was opened and it doesn't fit into the design philosophy of MPF now.
