### ISSUE TITLE
VideoNow discs are not populating DIC flags properly

### ISSUE THREAD

**Issue by putnam** [SabreTools/MPF#307]
When you select any of the VideoNow systems in the MPF dropdown, the /vn, /vnc, and /vnx flags are not correctly added to the DIC command line. Dumps without these flags are not complete and thus not admissable to Redump.

Looks like this section needs to add the relevant flags for each:
https://github.com/SabreTools/MPF/blob/c4793e849cbb84b0eaa00d4efe7a37410cf124e7/MPF.Library/DiscImageCreator/Parameters.cs#L1661

**Comment by mnadareski** [comment]
This is intentional as those flags do not function as intended according to people who know far more than I do. I will re-enable those flags once they are fixed.

**Comment by putnam** [comment]
I had some dumps denied for the flag missing, and was told to redo them with the relevant flag, so I don't know what's going on. Is there some documentation or a forum thread or something you can link about this?

**Comment by mnadareski** [comment]
As far as I know, it's mentioned a couple of times in the official DiscImageCreator thread on Redump. Part of the problem is that the value is not static for any of those and therefore needs two dumps in a row to get the value. Feel free to ask on the official thread: http://forum.redump.org/topic/10483/discimagecreator/
