### ISSUE TITLE
[Problem] I'm trying to rip m$ iso from original disc and it keeps showing cmd screen pops up and then disappear

### ISSUE THREAD

**Issue by DEVUVO** [SabreTools/MPF#413]
[Problem]
Hello , i need help 
 I'm trying to rip m$ iso from original disc i wanted to keep original disc hashes and it keeps showing cmd screen pops up and then disappear

thanks

**Comment by mnadareski** [comment]
Unfortunately, your bug is vague at best as to what is going on. Since it's unclear what sort of Microsoft disc you're talking about (whether it's a PC disc or something for an Xbox series console), I'll provide what information I can.

DiscImageCreator, the program that MPF uses to dump by default, has a limitation on what drives are supported for different media types. Please see this page for information on compatible drives for both CDs and Xbox console games: http://wiki.redump.org/index.php?title=DiscImageCreator:_Optical_Disc_Drive_Compatibility

**Comment by mnadareski** [comment]
Please reopen this in the future if the above advise didn't end up helping.
