### ISSUE TITLE
[Problem] MPF 2.4-1033 NET 6.0 x64 just shuts down

### ISSUE THREAD

**Issue by Ragowit** [SabreTools/MPF#457]
**Version**
- [x] WIP release (2.4-1033 NET 6.0 x64)

**Build**
- [x] .NET 6.0 running on Win 11, 22H2

**Describe the issue**
MPF just shuts down when I try to start it. WIP MPF 2.4-1033 NET 4.8 works just fine.

**To Reproduce**
1. Double click the MPF.exe
2. See the MPF window for a brief second before it shuts down.

**Expected behavior**
MPF window to stay open

**Comment by mnadareski** [comment]
Partially addressed as of https://github.com/SabreTools/MPF/commit/2a544676e6288ebf0ae1ad7f41f7046da8cda8f8

This is more of a temporary mitigation than anything. Still investigating otherwise.

**Comment by mnadareski** [comment]
The culprit, after a lot of debugging was `Microsoft.Management.Interface`. Interestingly, it would function perfectly fine if I didn't run `dotnet publish`, so local runs would all succeed. The issue stemmed from how MMI decided to bundle its native DLLs, that is, by much more specific runtime identifiers. Because of that, I have decided to move to the more granular runtime identifiers across the board. These changes are reflected in https://github.com/SabreTools/MPF/commit/b428bc0ba0573d86cb85211227d4b0513cdddcb2

Please try out the AppVeyor build that corresponds to your system and please report back.
