### ISSUE TITLE
[Problem] Doesn't detect an incomplete redumper DVD dump

### ISSUE THREAD

**Issue by DopefishJustin** [SabreTools/MPF#500]
**Version**
- [x] WIP release 2.5-1126

**Build**
What runtime version are you using?

- [x] .NET Framework 4.8 running on Windows 10

**Describe the issue**
MPF does not seem to detect the redumper process terminating before it finishes, and proceeds as if the dump were successful.

**To Reproduce**
1. Insert a DVD (I used an IBM PC compatible one)
2. Scan for discs
3. Select redumper as the dumping program
4. Begin a dump
5. Click X to close the redumper console window
6. Note that MPF continues with the protection check and the submission info window

**Expected behavior**
Red text in the output window indicating a failure

**Additional context**
Works as expected when dumping a CD with redumper.

**Comment by mnadareski** [comment]
This is going to be difficult because the only thing that MPF looks for in a "completed" dump is one that contains all of the files that are necessary. If Redumper is creating all files off the bat, then it will pretty much always say that it's "complete". Not sure how to get around this, to be honest. Leaving it open, though, because it is an issue.

**Comment by mnadareski** [comment]
Possibly fixed by https://github.com/SabreTools/MPF/commit/8a5475380a0c318ed34b74724ea300d67d04411e

**Comment by DopefishJustin** [comment]
Confirmed fixed in [8a547538](https://github.com/SabreTools/MPF/commit/8a5475380a0c318ed34b74724ea300d67d04411e)
