### ISSUE TITLE
[Request] Remove support for DiscImageCreator

### ISSUE THREAD

**Issue by tjanas** [SabreTools/MPF#527]
**Is your feature request related to a problem? Please describe.**
DiscImageCreator is a problem.

**Describe the solution you'd like**
Redumper supporting all discs currently supported by DiscImageCreator.

**Describe alternatives you've considered**
Pretend DiscImageCreator is awesome.

**Additional context**
Support shouldn't be removed until additional disc types are fully-supported by redumper.

**Comment by mnadareski** [comment]
Additional note for the future: this will only pertain to dumping support via the UI. Check support would likely remain to support those who need it transitionally.

**Comment by Deterous** [comment]
Alternative: No longer bundle DIC with MPF UI builds, but if MPF detects DIC in the Path provided in the Options, then allow the user to dump with DIC.

**Comment by Deterous** [comment]
#654 hides DIC as an option for dumping program from the main window completely if any future MPF builds don't bundle DIC.
So at any point in the future, this issue can be completely solved by removing DIC from the appveyor build script for WIP builds and/or not bundling it with Release builds.

I would consider it an undesirable change if DIC support were ripped out of the MPF UI, this soft solution allows for advanced users to keep using DIC with MPF if they know what they are doing and install DIC manually.

**Comment by mnadareski** [comment]
No solution to this can be done until Redumper has XGD1/2/3 support to put it on par with DIC. DIC is required for those disc types at the moment.

**Comment by Deterous** [comment]
DIC currently supports XGD1/2/3 via Kreon or swap disc method (for GSA-4163B supposedly). Does MPF currently even support the swap disc method for xbox?
DIC claims to support GC/Wii with supported drives, as well as the slow method with Plextors. Does Redumper have at least parity for these?
DIC supports the PS3 drive for dumping PS3 discs, would be good if Redumper supported that drive before MPF dropped DIC support.
DIC also *technically* has SACD support, however untested that may be. Redumper would ideally support that too, before dropping DIC.

**Comment by maxz** [comment]
There are still way too many issues with Redumper, even with plain CDs and DVDs. Thinking that it could currently fully replace DiscImageCreator is nothing short of delusional. And yet you opened this issue in 2023 when the situation was even worse. We need both for the foreseeable future.

I'm in the process of redumping my previous DIC dumps with DIC and Redumper and I regularly come across discrepancies between the two. Sometimes it's down to the respective author's worldview and not an issue. Other times it's a serious issue. Most of the real issues I encountered were or are connected to DVDs.

**Comment by mnadareski** [comment]
Thank you for weighing in on the issue. It seems like you may not have the same context that both myself and the original author of this issue had. This was not meant to be something implemented at the time it was opened, rather, a long-term item that could be worked on iteratively as Redumper improved. There are many areas where Redumper has already caught up to or exceeded functionality compared to DIC. There are also many places that it has not quite caught up (e.g. XGD1/2/3). Given the length of development time that both programs have had, this is both understandable and expected.

I would like to request that any future feedback not make ad hom attacks against anyone else who comments in this thread, such as calling this "delusional". Both programs can and will be supported into the forseeable future, with less of an emphasis on doing the extra work to support newer DIC functionality and outputs given the variability.

**Comment by Deterous** [comment]
Just to add some points you may be missing:
1. As previously mentioned, MPF would not immediately remove DIC dumping support in the UI, but no longer bundle it. As well, it would remain supported by MPF.Check as it is understood that there will remain cases where DIC is used for dumping even if Redumper supersedes it in the vast majority of cases.
2. MPF is primarily developed for the redump project, and therefore, DIC dumping will be supported by MPF as long as it is still required/recommended by the redump project.

**Comment by maxz** [comment]
> [...] It seems like you may not have the same context that both myself and the original author of this issue had. [...]
> 
> I would like to request that any future feedback not make ad hom attacks against anyone else who comments in this thread, such as calling this "delusional". [...]

I apologise. It was a bit harsh and prompted by the perceived sassy writing of the initial post together with my experience about the still existent shortcomings.

But overall Redumper is on a very good path and as you wrote, there are things that it does better.


> 2. MPF is primarily developed for the redump project, and therefore, DIC dumping will be supported by MPF as long as it is still required/recommended by the redump project.

I use Aaru, DIC and Redumper together and report inconsistencies to the respective projects so that they can be evaluated and fixed. I'm exclusively using Linux, so my direct interest in MPF is not the highest, yet I have some interest because MPF 's submission files seem to be closely tied to the format expected for submissions to redump.org.
In parts MPF seems to implement some handed down format specified behind the scenes of the project which is not comprehensively documented in public (e. g. the tags) and in other parts the implementation in MPF seems to establish things as the new standard for submissions (e. g. the format for multiple different labels). Therefore I always have to be aware of how the current MPF submission format looks and which tools it supports, because I have to include my information appropriately in my submissions and want the redump.org database to be as accurate and comprehensive as feasible. And due to my wish for accuracy, I had to voice my concerns before any rash decisions would be made. With its big user base, MPF has the power to influence a lot.

I think it would be detrimental if DIC fell out of fashion at the current time, but this seems to be unlikely to happen according to your messages.

**Comment by NovaSAurora** [comment]
Re: Tags
http://wiki.redump.org/index.php?title=Special_Site_Codes

**Comment by maxz** [comment]
Thanks, I appreciate it. I had been looking in the forum and the wiki but could not find anything.

**Comment by mnadareski** [comment]
Item no longer relevant.
