### ISSUE TITLE
[Request] Add an option for redumper --drive-sector-order

### ISSUE THREAD

**Issue by GregWeil** [SabreTools/MPF#690]
My Pioneer drive doesn't support C2 error codes, so I have to specify `--drive-sector-order=DATA_SUB` on the command line every time. It'd be much more convenient if there was a dropdown for the sector order alongside the existing BE_CDDA option.

Alternatively, a way to specify misc extra params to always get added on to the command line would also be nice.

**Comment by mnadareski** [comment]
I'm sorry, but for the primary use of this frontend, having this be a configurable option for most people would make thins more difficult. Having configurable extra params is possible in the future, but it is not currently being looked at. I will mark this as "help wanted" if anyone is willing to do the second option.

**Comment by Deterous** [comment]
The current options for BE_CDDA and GENERIC contradicts the reason for not having DATA_SUB as an option. In fact, BE_CDDA and GENERIC options have already caused issues for redump in the past due to users previously ticking them then later using a different drive. I suggest the sector order be hidden behind an advanced options / non-redump mode warning, alongside read method and generic drive type.

Of course, I'll also implement this, not just suggest it.
