### ISSUE TITLE
[Problem] MPF.CLI Linux 64-bit -lc, -lm, -ls, -lp do not exit

### ISSUE THREAD

**Issue by Barthax** [SabreTools/MPF#753]
**Version**

- [X] Stable release (3.2.2 CLI)
- [ ] WIP release (version here)

**Build**
What runtime version are you using?

- [X] .NET 8.0 running on Linux 64-bit

**Describe the issue**
Running any of the List command lines options in MPF.CLI and the program continues running without exiting.

**To Reproduce**

1. MPF.CLI -lc
2. It keeps on running.

**Expected behavior**
Program exits.

**Comment by mnadareski** [comment]
I'm going to assume you're seeing that it's waiting for any user input. This was originally done in order to make it easier for users to catch the whole list, but I guess now that people are actually using these programs, it may look more confusing. The two options I have are ensuring that a message is shown such as "Press Enter to continue" or just remove the wait for entry entirely. I am going to go with the latter since this could interfere with output redirection.

**Comment by mnadareski** [comment]
Fixed by https://github.com/SabreTools/MPF/commit/51733557cd15101f09a77b120ff158231b5fcd20
