### ISSUE TITLE
[Info] Securom capitalization differs between DIC and Redumper

### ISSUE THREAD

**Issue by FoxhackDN** [SabreTools/MPF#757]
**Is your information related to one of the dumping programs supported or something that isn't a bug in the code? Please describe.**
Using MPF 3.2.2, you get slighty different results in the submission info if you dump a disc with Securom v7:

DIC:
`MSF: 00:01:74 Q-Data: 410100 00:40:01 00 00:03:74 2ef1`

Redumper:
`MSF: 00:01:74 Q-Data: 410100 00:40:01 00 00:03:74 2EF1`

**Additional context**
There is no functional difference between the two results, but I don't know which one is *preferred* and Sabre told me to post this here so yeah.

**Comment by mnadareski** [comment]
After talking about this with the other Redump moderators, we have decided that this does not need to be normalized. The values are effectively identical and are normalized on Redump's site. Since this is the primary use case for MPF, I will be closing this but leaving the issue here in case others happen to notice it as well.
